/**
 * Generates public/sitemap.xml and public/robots.txt from the app's public URL inventory.
 *
 * URL list: src/lib/seo/publicUrlInventory.ts → buildPublicUrlInventory()
 * Commands:  npm run seo:generate | npm run seo:verify
 *
 * Do not edit public/sitemap.xml or public/robots.txt by hand.
 */
import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import {
  buildPublicUrlInventory,
  CANONICAL_HOST,
  ROBOTS_DISALLOW_PATHS,
  SITEMAP_EXCLUDED_PATHS,
  getSitemapChangefreq,
  getSitemapPriority,
} from "../src/lib/seo/publicUrlInventory";

function todayUtc(): string {
  return new Date().toISOString().slice(0, 10);
}

function escapeXml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function renderSitemap(urls: string[], lastmod: string): string {
  const entries = urls
    .map((loc) => {
      const path = new URL(loc).pathname || "/";
      const changefreq = getSitemapChangefreq(path);
      const priority = getSitemapPriority(path).toFixed(2);
      return `  <url>
    <loc>${escapeXml(loc)}</loc>
    <lastmod>${lastmod}</lastmod>
    <changefreq>${changefreq}</changefreq>
    <priority>${priority}</priority>
  </url>`;
    })
    .join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${entries}
</urlset>
`;
}

function renderRobots(): string {
  const disallowLines = ROBOTS_DISALLOW_PATHS.map(
    (path) => `Disallow: ${path}`
  ).join("\n");

  return `# Generated by scripts/generate-seo.ts - do not edit by hand
# Canonical: ${CANONICAL_HOST}

User-agent: *
Allow: /

${disallowLines}

Sitemap: ${CANONICAL_HOST}/sitemap.xml
`;
}

async function main() {
  const inventory = buildPublicUrlInventory();
  const lastmod = todayUtc();
  const publicDir = join(process.cwd(), "public");

  await mkdir(publicDir, { recursive: true });

  const sitemapPath = join(publicDir, "sitemap.xml");
  const robotsPath = join(publicDir, "robots.txt");

  const sitemapXml = renderSitemap(inventory.allUrls, lastmod);
  const robotsTxt = renderRobots();

  await writeFile(sitemapPath, sitemapXml, "utf8");
  await writeFile(robotsPath, robotsTxt, "utf8");

  console.log("SEO files generated");
  console.log("─".repeat(40));
  console.log(`Canonical host: ${CANONICAL_HOST}`);
  console.log(`Last modified:  ${lastmod}`);
  console.log(`Sitemap URLs:   ${inventory.counts.total}`);
  console.log(`  Static pages: ${inventory.counts.static}`);
  console.log(`  Case types:   ${inventory.counts.caseTypes}`);
  console.log(`  Guides:       ${inventory.counts.guides}`);
  console.log(`  Services:     ${inventory.counts.services}`);
  console.log(`Excluded:       ${SITEMAP_EXCLUDED_PATHS.join(", ")}`);
  console.log(`Robots block:   ${ROBOTS_DISALLOW_PATHS.join(", ")}`);
  console.log("─".repeat(40));
  console.log(`Wrote ${sitemapPath}`);
  console.log(`Wrote ${robotsPath}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
